name: BuyAbilities
version: 0.8.9
main: com.rcjrrjcr.bukkitplugins.buyabilitiesplugin.BuyAbilities
description: Allows the purchase of temporary abilities with iConomy money.
database: false
author: rcjrrjcr
commands: 
    buyabilities: 
        aliases:
            - bab
            - buyab
        description: Manage and buy abilities
        usage: /buyab [categories|category|page|current|buy|rent|rentuse|info|help]